defaultPortal: zepedro
portals:
  - name: zepedro
    portalId: 23461626
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJCEuN7TMBILAA0AAAAA4A0AQAIY-v2XCyDZ5PgWKO7pDDIUgd_NfnbKE7d7P0jwPmAWzYWS5no6KAAABEEAAAB4AAAAAAAAAAAAAAAAAAAABAAAwAcA_v8xPAAAAABEAGBCFInXb6GDeoTBEdEX7YLki9E2VJAqSgNuYTFSAFoA
        expiresAt: '2022-12-22T21:47:14.836Z'
    personalAccessKey: >-
      CiRiYjhiMjk4Yi0wMjE5LTQyYjYtYTFhMS1jMTU0OWE4MzdmNTkQ-v2XCxjZ5PgWKhkABeaRgjWVUycv0b7SPAwRNLtJI4yXsF4FSgNuYTE
