defaultPortal: zepedro
portals:
  - name: zepedro
    portalId: 23461626
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CN3J1ojUMBILAA0AAAAA4A0AQAIY-v2XCyDZ5PgWKO7pDDIU7TPoix1XSU-P-S20qNj6cy5OJUg6KAAABEEAAAB4AAAAAAAAAAAAAAAAAAAABAAAwAcA_v8xPAAAAABEAGBCFFQfwSTa4Oo6UUF11z83P3r9ASgcSgNuYTFSAFoA
        expiresAt: '2022-12-23T22:23:35.649Z'
    personalAccessKey: >-
      CiRiYjhiMjk4Yi0wMjE5LTQyYjYtYTFhMS1jMTU0OWE4MzdmNTkQ-v2XCxjZ5PgWKhkABeaRgjWVUycv0b7SPAwRNLtJI4yXsF4FSgNuYTE
