defaultPortal: zepedro
portals:
  - name: zepedro
    portalId: 23461626
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJLW96DVMBILAA0AAAAA4A0AQAIY-v2XCyDZ5PgWKO7pDDIU8qxYDCR6GqXgp404NJ8tuNNj4Wc6KAAABEEAAAB4AAAAAAAAAAAAAAAAAAAABAAAwAcA_v8xPAAAAABEAGBCFH4muBhkoTkEo3UCj-y2i_uTKnprSgNuYTFSAFoA
        expiresAt: '2022-12-27T15:05:25.013Z'
    personalAccessKey: >-
      CiRiYjhiMjk4Yi0wMjE5LTQyYjYtYTFhMS1jMTU0OWE4MzdmNTkQ-v2XCxjZ5PgWKhkABeaRgjWVUycv0b7SPAwRNLtJI4yXsF4FSgNuYTE
