defaultPortal: zepedro
portals:
  - name: zepedro
    portalId: 23461626
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CICwmqDWMBILAA0AAAAA4A0AQAIY-v2XCyDZ5PgWKO7pDDIUVtt_tHTpXoqlKTfdpzO2VFKgUTI6KAAABEEAAAB4AAAAAAAAAAAAAAAAAAAABAAAwAcA_v8xPAAAAABEAGBCFAiqaxySEVDJhI-s1Pm45pRysREqSgNuYTFSAFoA
        expiresAt: '2022-12-30T17:13:51.877Z'
    personalAccessKey: >-
      CiRiYjhiMjk4Yi0wMjE5LTQyYjYtYTFhMS1jMTU0OWE4MzdmNTkQ-v2XCxjZ5PgWKhkABeaRgjWVUycv0b7SPAwRNLtJI4yXsF4FSgNuYTE
